version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: frontend
    depends_on:
      - backend
    networks:
      - swiftshort-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"
    container_name: backend
    restart: always
    networks:
      - swiftshort-network

networks:
  swiftshort-network:
