version: '3'

services:
  frontend:
    build:
      context: ./src
      dockerfile: Frontend.Dockerfile
    ports:
      - "4000:80"
    container_name: frontend
    depends_on:
      - backend
    networks:
      - swiftshort-network

  redis:
    image: "redis/redis-stack:latest"
    container_name: "redis-container"
    ports:
      - "6379:6379"
      - "8001:8001"

  backend:
    build:
      context: ./src
      dockerfile: Backend.Dockerfile
    ports:
      - "3000:3000"
    container_name: backend
    restart: always
    networks:
      - swiftshort-network

networks:
  swiftshort-network:
